export const Gallery: Record<string, string[]> = {
  entoto: [
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/1.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/2.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/3.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/4.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/5.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/6.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/7.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/8.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/9.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/10.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/11.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/12.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/13.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/14.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/15.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/16.JPG",
  ],

  bishoftu: [
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/2.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/3.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/4.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/5.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/6.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/7.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/8.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/10.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/11.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/12.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/13.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/14.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/15.JPG",
  ],

  laketana: [
    "https://kurifturesorts.com/_nuxt/img/soci.76a5a73.webp",
    "https://kurifturesorts.com/_nuxt/img/bd.654e148.webp",
    "https://kurifturesorts.com/_nuxt/img/1.6d55bab.webp",
    "https://kurifturesorts.com/_nuxt/img/BirdWatching.75afd69.webp",
    "https://kurifturesorts.com/_nuxt/img/ConferenceHall.f84c697.webp ",
    "https://kurifturesorts.com/_nuxt/img/LakeSide.01bf8ea.webp",
  ],
  awash: [
    "https://kurifturesorts.com/_nuxt/img/1.cba30ab.webp",
    "https://kurifturesorts.com/_nuxt/img/2.d4feaba.webp",
    "https://kurifturesorts.com/_nuxt/img/TheFallsRestaurant&Bar.69968c3.webp",
    "https://kurifturesorts.com/_nuxt/img/4.33fc8c3.webp",
    "https://kurifturesorts.com/_nuxt/img/5.9fafbdc.webp",
    "https://kurifturesorts.com/_nuxt/img/jun1.6e87593.webp",
    "https://kurifturesorts.com/_nuxt/img/3.1b81bb4.webp",
  ],
  africanVillage: [
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/1.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/2.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/3.JPG",
  ],
  waterpark: [
    "https://kurifturesorts.com/_nuxt/img/_DSC5641%20(2)-min.f32edfd.jpg",
    "https://kurifturesorts.com/_nuxt/img/waterpark2.7574045.jpg",
    "https://kurifturesorts.com/_nuxt/img/kuriftu%20dec%2022-5391-min%20(1).5f30be4.jpg",
    "https://kurifturesorts.com/_nuxt/img/kuriftu%20dec%2022-5422-min%20(1).e20e04c.jpg",
    "https://kurifturesorts.com/_nuxt/img/dinslide2.ca27dc6.webp",
    "https://kurifturesorts.com/_nuxt/img/KuriftuBuffet.ed0beaf.webp",
    "https://kurifturesorts.com/_nuxt/img/_DSC5820%20(2)-min.c7b8704.jpg",
    "https://kurifturesorts.com/_nuxt/img/TreatByThePorch.df2143d.webp",
    "https://kurifturesorts.com/_nuxt/img/dinslide5.e0dfde1.webp",
  ],
  boston: [
    "https://kuriftu-public-media.s3.amazonaws.com/boston/1.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/2.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/3.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/4.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/5.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/6.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/7.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/8.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/9.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/10.jpg",

  ],
};
