export const Gallery: Record<string, string[]> = {
  entoto: [
    "https://kuriftu-public-media.s3.amazonaws.com/Entoto/entoto24.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/Entoto/entoto4.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/4.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/5.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/6.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/7.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/8.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/9.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/10.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/11.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/12.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/13.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/entoto/14.JPG",
   //"https://kuriftu-public-media.s3.amazonaws.com/entoto/15.JPG",
   // "https://kuriftu-public-media.s3.amazonaws.com/entoto/16.JPG",
  ],

  bishoftu: [
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu7.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu12.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu_cover.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu2.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu5.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu11.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu15.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu20.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/11.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/12.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/14.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/15.JPG",
  ],

  laketana: [
    "https://kuriftu-public-media.s3.amazonaws.com/tana/1.webp",
    "https://kuriftu-public-media.s3.amazonaws.com/tana/2.webp",
    "https://kuriftu-public-media.s3.amazonaws.com/tana/3.webp",
    "https://kuriftu-public-media.s3.amazonaws.com/tana/4.webp",
    "https://kuriftu-public-media.s3.amazonaws.com/tana/5.webp",
    "https://kuriftu-public-media.s3.amazonaws.com/tana/6.webp",
  ],
  awash: [
    "https://kurifturesorts.com/_nuxt/img/1.cba30ab.webp",
    "https://kurifturesorts.com/_nuxt/img/2.d4feaba.webp",
    "https://kurifturesorts.com/_nuxt/img/TheFallsRestaurant&Bar.69968c3.webp",
    "https://kurifturesorts.com/_nuxt/img/4.33fc8c3.webp",
    "https://kurifturesorts.com/_nuxt/img/5.9fafbdc.webp",
    "https://kurifturesorts.com/_nuxt/img/jun1.6e87593.webp",
    "https://kurifturesorts.com/_nuxt/img/3.1b81bb4.webp",
  ],
  africanVillage: [
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/1.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/5.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/3.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/4.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/10.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/6.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/7.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/8.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/9.JPG",
    "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/2.JPG",
  ],
  waterpark: [
    "https://kuriftu-public-media.s3.amazonaws.com/waterpark/waterpark1.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/waterpark/waterpark2.jpg",
    "https://kurifturesorts.com/_nuxt/img/waterpark2.7574045.jpg",
    "https://kurifturesorts.com/_nuxt/img/kuriftu%20dec%2022-5422-min%20(1).e20e04c.jpg",
    "https://kurifturesorts.com/_nuxt/img/dinslide2.ca27dc6.webp",
    "https://kurifturesorts.com/_nuxt/img/KuriftuBuffet.ed0beaf.webp",
    "https://kurifturesorts.com/_nuxt/img/_DSC5820%20(2)-min.c7b8704.jpg",
    "https://kurifturesorts.com/_nuxt/img/TreatByThePorch.df2143d.webp",
    "https://kurifturesorts.com/_nuxt/img/dinslide5.e0dfde1.webp",
  ],
  boston: [
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston14.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston17.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston6.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston20.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston22.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston24.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston27.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston35.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston37.jpg",
    "https://kuriftu-public-media.s3.amazonaws.com/boston/boston32.jpg",

  ],
};
