export const Gallery: Record<string, string[]> = {
  entoto: [
    "/entoto/1.jpg",
    "/entoto/2.JPG",
    "/entoto/3.JPG",
    "/entoto/4.jpg",
    "/entoto/5.jpg",
    "/entoto/6.jpg",
    "/entoto/7.JPG",
    "/entoto/8.JPG",
    "/entoto/9.jpg",
    "/entoto/10.jpg",
    "/entoto/11.JPG",
    "/entoto/12.JPG",
    "/entoto/13.JPG",
    "/entoto/14.JPG",
    "/entoto/15.JPG",
    "/entoto/16.JPG",
  ],

  bishoftu: [
    "/bishoftu/2.JPG",
    "/bishoftu/3.JPG",
    "/bishoftu/4.JPG",
    "/bishoftu/5.jpg",
    "/bishoftu/6.JPG",
    "/bishoftu/7.JPG",
    "/bishoftu/8.JPG",
    "/bishoftu/10.JPG",
    "/bishoftu/11.JPG",
    "/bishoftu/12.JPG",
    "/bishoftu/13.JPG",
    "/bishoftu/14.JPG",
    "/bishoftu/15.JPG",
  ],

  laketana: [
    "https://kurifturesorts.com/_nuxt/img/soci.76a5a73.webp",
    "https://kurifturesorts.com/_nuxt/img/bd.654e148.webp",
    "https://kurifturesorts.com/_nuxt/img/1.6d55bab.webp",
    "https://kurifturesorts.com/_nuxt/img/BirdWatching.75afd69.webp",
    "https://kurifturesorts.com/_nuxt/img/ConferenceHall.f84c697.webp ",
    "https://kurifturesorts.com/_nuxt/img/LakeSide.01bf8ea.webp",
  ],
  awash: [
    "https://kurifturesorts.com/_nuxt/img/1.cba30ab.webp",
    "https://kurifturesorts.com/_nuxt/img/2.d4feaba.webp",
    "https://kurifturesorts.com/_nuxt/img/TheFallsRestaurant&Bar.69968c3.webp",
    "https://kurifturesorts.com/_nuxt/img/4.33fc8c3.webp",
    "https://kurifturesorts.com/_nuxt/img/5.9fafbdc.webp",
    "https://kurifturesorts.com/_nuxt/img/jun1.6e87593.webp",
    "https://kurifturesorts.com/_nuxt/img/3.1b81bb4.webp",
  ],
  africanVillage: [
    "/africanvillage/1.JPG",
    "/africanvillage/2.JPG",
    "/africanvillage/3.JPG",
  ],
  waterpark: [
    "https://kurifturesorts.com/_nuxt/img/_DSC5641%20(2)-min.f32edfd.jpg",
    "https://kurifturesorts.com/_nuxt/img/waterpark2.7574045.jpg",
    "https://kurifturesorts.com/_nuxt/img/kuriftu%20dec%2022-5391-min%20(1).5f30be4.jpg",
    "https://kurifturesorts.com/_nuxt/img/kuriftu%20dec%2022-5422-min%20(1).e20e04c.jpg",
    "https://kurifturesorts.com/_nuxt/img/dinslide2.ca27dc6.webp",
    "https://kurifturesorts.com/_nuxt/img/KuriftuBuffet.ed0beaf.webp",
    "https://kurifturesorts.com/_nuxt/img/_DSC5820%20(2)-min.c7b8704.jpg",
    "https://kurifturesorts.com/_nuxt/img/TreatByThePorch.df2143d.webp",
    "https://kurifturesorts.com/_nuxt/img/dinslide5.e0dfde1.webp",
  ],
  boston: [
    "/boston/1.JPG",
    "/boston/2.JPG",
    "/boston/3.JPG",
    "/boston/4.JPG",
    "/boston/5.JPG",
    "/boston/6.JPG",
    "/boston/7.JPG",
    "/boston/8.JPG",
    "/boston/9.JPG",
    "https://kurifturesorts.com/_nuxt/img/24.9dfafe2.jpg",
    "https://kurifturesorts.com/_nuxt/img/25.458bb05.jpg",
    "https://kurifturesorts.com/_nuxt/img/26.a81e8e3.jpg",
    "https://kurifturesorts.com/_nuxt/img/27.cc2beb9.jpg",
  ],
};
