import { ResortDetailsModal } from "../interfaces/resortDetailModal";


export const RESORTDETAILS: Record<string, ResortDetailsModal> = {
  entoto: {
    name: "Kuriftu Resort & Spa Entoto",
    region: "ENTOTO NATIONAL PARK, ADDIS ABABA",
    address: "321 Lake View Avenue, Bishoftu, Ethiopia",
    description: "Cradled within the whispering eucalyptus of Entoto Mountain, Kuriftu Entoto reveals Ethiopia’s soul through elemental adventure. Here, where Emperor Menelik II once gazed upon the birth of Addis Ababa, guests traverse forested paths on horseback, scale ancient stone, and dwell beneath starlit skies in secluded tents. A sacred land of history and breath, inviting quiet wonder, familial connection, and communion with nature’s unspoken rhythm.",
    phone: "+2519 05 061020, +2519 11 091185",
    latitude: 9.0846279,
    longitude: 38.7383589,
    location: "https://www.google.com/maps/place/Kuriftu+Entoto+Resort+and+Spa/@9.0782278,38.7401494,17z/data=!4m10!3m9!1s0x164b8fe9784c22b1:0xb585017862062bdb!5m3!1s2025-04-11!4m1!1i2!8m2!3d9.0782278!4d38.7427243!16s%2Fg%2F11jzfb8yfm?entry=ttu&g_ep=EgoyMDI1MDQwMi4xIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image: "https://kuriftu-public-media.s3.amazonaws.com/Entoto/entoto23.jpg",
    cover_video: "https://kuriftu-public-media.s3.amazonaws.com/entoto/Entoto+720p.mp4",
    isIframe: false,
    direction: "14.9 km from Addis Ababa Bole International Airport, Entoto Park, Ethiopia",
  },
  bishoftu: {
    isIframe: false,
    name: "Kuriftu Resort & Spa Bishoftu",
    region: "Bishoftu, Oromia",
    address: "",
    direction:"53.8 km from Addis Ababa Bole International Airport, Lake Bishoftu, Ethiopia",
    description: "Set against the tranquil shores of Bishoftu, Kuriftu Resort unfolds amidst the peaceful embrace of nature. Its elegant suites, nestled in harmony with the landscape, offer serene views of the lake’s reflective waters. A haven of calm, the resort invites you to wander beneath towering trees, where each moment feels suspended in time, and the essence of Ethiopia’s rich heritage gently weaves through every experience.",
    phone: "+2519 24 949494,+2519 11 091185",
    latitude: 8.779961,
    longitude: 39.003129,
    location:
      "https://www.google.com/maps/place/Kuriftu+Resort+%26+Spa+Bishoftu/@8.7802656,39.0002894,17z/data=!3m1!4b1!4m9!3m8!1s0x164b0cba1728a73d:0x44f92b98676731e7!5m2!4m1!1i2!8m2!3d8.7802656!4d39.0028643!16s%2Fg%2F11c5bty0tz?entry=ttu&g_ep=EgoyMDI1MDQwMi4xIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image: "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu14.jpg",
    cover_video: "https://kuriftu-public-media.s3.amazonaws.com/bishoftu/bishoftu720.mp4",
  },
  laketana: {
    isIframe: true,
    name: "Kuriftu Resort & Spa Lake Tana",
    region: "BAHIRDAR",
    address: "",
    direction: "491 km from Addis Ababa Bole International Airport Lake Tana, Ethiopia",
    description:"Nestled in Bahir Dar, the heart of the Amhara Region, Kuriftu Resort & Spa Lake Tana marks a serene extension of our vision. Surrounded by timeless beauty, rich history, and sacred landscapes, this sanctuary invites guests to immerse in the essence of Ethiopia. With tranquil waters, wildlife encounters, and spiritual journeys, Lake Tana is a place of profound discovery, where nature and culture intertwine harmoniously.",
    phone: "+2519 20 959797,+2519 11 091185",
    latitude: 11.598445,
    longitude: 37.383701,
    location:
      "491 km from Addis Ababa Bole International AirportLake Tana Ethiopia",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image: "https://kuriftu-public-media.s3.amazonaws.com/tana/9.webp",
    cover_video:
      "https://kuriftu-public-media.s3.amazonaws.com/tana/tana720p.mp4",
  },
  awash: {
    isIframe: true,
    name: "Kuriftu Resort & Spa Awash Falls",
    region: "AWASH NATIONAL PARK",
    address: "",
    description:
      "Located on the Southern tip of Awash National Park, our one-of-a-kind boutique resort suspended over a waterfall places guests at an elevation that is unique to our property. With views of crocodiles on the river bank, the refreshing mist from the edge of the falls paired with unmatched scenery, we offer the ultimate experience to our visitors",
    phone: "+251944448800",
    latitude: 8.779961,
    longitude: 39.003129,
    location:
      "https://www.google.com/maps/place/Kuriftu+Resort+%26+Spa+Awash+Falls/@8.8430524,40.0097226,17z/data=!3m1!4b1!4m9!3m8!1s0x163593fea245879f:0xca93c0e4241369ec!5m2!4m1!1i2!8m2!3d8.8430524!4d40.0122975!16s%2Fg%2F11swpb3900?entry=ttu&g_ep=EgoyMDI1MDQwMi4xIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D",
    email: "booking@kurifturesorts.com",
    rating: 5,
    cover_image:
      "https://kuriftu-public-media.s3.amazonaws.com/awash/awash3.webp",
    cover_video:
      "https://kuriftu-public-media.s3.amazonaws.com/awash/awash_720P.mp4",
  },
  africanVillage: {
    isIframe: false,
    name: "Kuriftu Resort & Spa African Village",
    region: "Melka Nuno, Sheger City",
    address: "Melka Nuno, Sheger City, Oromia",
    description:"A quiet homage to the continent’s soul—Kuriftu Resort & Spa African Village unveils 54 villas, each a tender reflection of a nation’s spirit. Within, traditions breathe through handwoven fabrics, ancestral art, and the scent of native cuisine. This is not simply a resort, but a journey across Africa’s cultural heartbeat—an invitation to dwell in her stories, her rhythms, her quiet, radiant grace.",
    phone: "+251924949494",
    latitude: 9.03,
    longitude: 38.74,
    location: "https://www.google.com/maps/place/Kuriftu+Resort+%26+Spa+African+Village/@9.0350944,38.6755992,17z/data=!3m1!4b1!4m9!3m8!1s0x164b87ea0f1d0525:0x4a24253e0a125b37!5m2!4m1!1i2!8m2!3d9.0350944!4d38.6781741!16s%2Fg%2F11sbh9b4y8?entry=ttu&g_ep=EgoyMDI1MDQwMi4xIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D",
    email: "booking@kurifturesorts.com",
    rating: 0,
    cover_image: "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/africa22.jpg",
    cover_video: "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/african_village720p.mp4",
    direction:"20.7  km from Addis Ababa Bole International Airport, Melka Nuno Sheger City, Oromia"
  },
  waterpark: {
    isIframe: false,
    name: "kuriftu Water Park",
    region: "Bishoftu",
    address: "53.7 km from Addis Ababa Bole International Airport",
    description:"Looking for a splash-tastic way to spend the day with your family? Whether you're planning a weekend adventure, a birthday bash, a group outing, or a surprise for someone special, Kuriftu Water Park is the perfect place for nonstop fun! Get ready to dive into excitement, ride the waves, and make unforgettable memories—because here, the fun never runs dry! ",
    phone: "+251924949494",
    latitude: 9.03,
    longitude: 38.74,
    location: "https://www.google.com/maps/place/Kuriftu+Water+Park/@8.7817245,39.0003685,17z/data=!3m1!4b1!4m6!3m5!1s0x164b0da06ed09677:0x145b79037fab1f1c!8m2!3d8.7817245!4d39.0029434!16s%2Fg%2F11fn98cw5x?entry=ttu&g_ep=EgoyMDI1MDQwMi4xIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D",
    email: "booking@kurifturesorts.com",
    rating: 0,
    cover_image: "https://kuriftu-public-media.s3.amazonaws.com/waterpark/waterpark3.jpg",
    cover_video: "https://kuriftu-public-media.s3.amazonaws.com/waterpark/water_park720.mov",
  },
  boston: {
    isIframe: false,
    name: "Boston Day Spa",
    region: "Bole, Addis Ababa",
    address: "53.7 km from Addis Ababa Bole International Airport",
    description:"Boston Day Spa is where the Kuriftu brand was born, a testament to our commitment to community empowerment. It is here that the spirit of our team took shape—dedicated artisans who once built this sanctuary by hand now deliver exceptional wellness experiences. What began as a capacity-building project in Addis Ababa has transformed into a sanctuary of well-being, showcasing the work of celebrated Ethiopian artists like Merikokeb Berhanu.",
    phone: "+251 11 662 3808, +251 11 663 6557",
    latitude: 9.03,
    longitude: 38.74,
    location: "https://www.google.com/maps/place/Boston+day+spa/@8.9894898,38.7781539,17z/data=!3m1!4b1!4m6!3m5!1s0x164b84fbfe0322b3:0xb0ee32bcc9ab1646!8m2!3d8.9894898!4d38.7807288!16s%2Fg%2F1tj5h6nb?entry=ttu&g_ep=EgoyMDI1MDQwMi4xIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D",
    email: "booking@kurifturesorts.com",
    rating: 0,
    cover_image: "https://kuriftu-public-media.s3.amazonaws.com/boston/boston16.jpg",
    cover_video: "https://kuriftu-public-media.s3.amazonaws.com/boston/Boston+Day+Spa+720p.mp4",
  }
};
