export const resortsAll = [
  {
    isShow: false,
    id: 1,
    name: "Boston Day Spa",
    slug: "boston",
    location: "Addis Abeba, Ethiopia",
    coordinates: [38.7578, 9.0301],
    image:
      "https://kuriftu-media-bucket.s3.us-east-1.amazonaws.com/object_media/resort/boston_day_spa/BOSTON%20DAY%20SPA%20_PIER%205%20STUDIOS_OCT-49.jpg",
  },
  {
    id: 2,
    isShow: true,
    name: "Entoto",
    slug: "entoto",
    location: "Addis Abeba, Ethiopia",
    coordinates: [38.7636, 9.069],
    image:
      "https://kuriftu-media-bucket.s3.us-east-1.amazonaws.com/object_media/resort/entoto/_DSC7949.jpg",
  },
  {
    id: 3,
    isShow: false,
    name: "Awash Falls",
    slug: "awash",
    location: "Awash, Ethiopia",
    coordinates: [39.9168, 8.9848],
    image: "https://kurifturesorts.com/_nuxt/img/barber.68d5290.webp",
  },
  {
    id: 4,
    isShow: true,
    name: "Bishoftu",
    slug: "bishoftu",
    location: "Bishoftu, Ethiopia",
    coordinates: [38.9785, 8.7542],
    image: "https://kurifturesorts.com/_nuxt/img/barber.68d5290.webp",
  },
  {
    isShow: false,
    id: 5,
    name: "Water Park",
    slug: "waterpark",
    location: "Water Park, Ethiopia",
    coordinates: [38.9785, 8.7542],
    image: "https://kurifturesorts.com/_nuxt/img/barber.68d5290.webp",
  },
  {
    id: 6,
    isShow: false,
    name: "Lake Tana",
    slug: "laketana",
    location: "Bahirdar, Ethiopia",
    coordinates: [37.3934, 11.6019],
    image: "https://kurifturesorts.com/_nuxt/img/barber.68d5290.webp",
  },
  {
    id: 7,
    isShow: true,
    name: "African Village",
    slug: "africanVillage",
    location: "Bahirdar, Ethiopia",
    coordinates: [9.0351536, 38.6786375],
    image: "https://kuriftu-public-media.s3.amazonaws.com/africanvillage/HomeAffricanVillage.svg",
  },
];
