name: Deploy React App to Test Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: CI=false npm run build

      - name: Verify Build Directory
        run: |
          if [ ! -d "build" ]; then 
            echo "Build directory not found! Build process may have failed.";
            exit 1;
          fi
      - name: Debug Secrets
        run: |
          echo "CPANEL_HOST is set: ${{ secrets.CPANEL_HOST != '' }}"
          echo "CPANEL_USERNAME is set: ${{ secrets.CPANEL_USERNAME != '' }}"
          echo "CPANEL_PASSWORD is set: ${{ secrets.CPANEL_PASSWORD != '' }}"

      - name: Upload to Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: build/
          server-dir: /
